# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER wsw

# 挂载目录
VOLUME /home/wsw
# 创建目录
RUN mkdir -p /home/wsw
# 指定路径
WORKDIR /home/wsw
# 复制jar文件到路径
COPY ./jar/wsw-modules-file.jar /home/wsw/wsw-modules-file.jar
# 启动文件服务
ENTRYPOINT ["java","-jar","wsw-modules-file.jar"]
