# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER wsw

# 挂载目录
VOLUME /home/wsw
# 创建目录
RUN mkdir -p /home/wsw
# 指定路径
WORKDIR /home/wsw
# 复制jar文件到路径
COPY ./jar/wsw-auth.jar /home/wsw/wsw-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","wsw-auth.jar"]
